### ISSUE TITLE
Feature: be able to use fixed version

### ISSUE THREAD

**Issue by ivanmarban** [release-flow/keep-a-changelog-action#65]
Thanks for making this great action! I found it very useful but I miss "more control" over the version instead of being calculated automatically.

Maybe the action could have a new `command` option `fixed` for example  and `version` then will accept the fixed semver string.

```yaml
- name: update changelog
  uses: release-flow/keep-a-changelog-action@v2
  with:
    command: fixed
    version: 1.0.0-rc.1
    tag-prefix: v
    changelog: CHANGELOG.md
    keep-unreleased-section: true
```
